DROP TABLE IF EXISTS EDITION;

CREATE TABLE EDITION(
id text PRIMARY KEY,
title text,
title_prefix text,
subtitle text,
other_titles[] text,
author_key text,
by_statement text,
publish_date text,
copyright_date text,
edition_name text,
language_key,
description text, 
notes text, 
genres[] text,
toc_class text,
toc_label text,
toc_title text,
toc_pagenum text,
work_titles[] text,
series[] text,
physical_dimensions text,
physical_format text,
number_of_pages integer,
subjects[] text,
pagination text,
lccn[] text,
ocaid text,
oclc_numbers[] text,
isbn_10[] text,
isbn_13[],
dewey_decimal_class[] text,
lc_classifications[] text,
contributions[] text,
publish_places[] text,
publish_country  text,
publishers[] text,
distributors[] text,
first_sentence text,
weight text,
location[] text,
scan_on_demand  boolean,
collection_name text,
uris[] text,
uri_descriptions[] text,
translation_of  text,
work_key text,
source_records[] text,
translated_key,
scan_records_key text,
volume_ia_id text,
volume_number integer,
accompanying_material text);
