DROP TABLE IF EXISTS WORKS;

CREATE TABLE WORKS(
id text PRIMARY KEY,
title text,
subtitle text,
author text,
--author_role text,
--author_as text,
translated_titles_language text,
translated_titles_text text,
subjects[] text,
subject_places[] text,
subject_times[] text,
subject_people[] text,
description text, 
dewey_number[] text,
lc_classifications[] text,
first_sentence  text,
original_languages_name text,
original_languages_code text,
original_languages_library_of_congress_name text,
other_titles[] text,
first_publish_date text,
links_url text,
links_title text,
notes text,
cover_edition text,
covers[] text);