DROP TABLE IF EXISTS AUTHORS; -- IF EXISTS

CREATE TABLE AUTHORS(
ID TEXT PRIMARY KEY,
NAME TEXT,
EASTERN_ORDER BOOLEAN,
PERSONAL_NAME TEXT,
ENUMERATION TEXT,
TITLE TEXT,
bio TEXT,
uris TEXT,
LOCATION TEXT,
BIRTH_DATE TEXT,
DEATH_DATE TEXT,
DATE TEXT,
WIKIPEDIA TEXT,
link TEXT,
links_title TEXT);

CREATE TABLE AUTHOR_ALT_NAME(
  ID_AUTHOR INT REFERENCES AUTHOR(ID),
  NAME TEXT NOT NULL
);

CREATE INDEX i1 ON AUTHOR_ALT_NAME(ID_AUTHOR);
